# Generated by Django 5.1.2 on 2024-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=50, verbose_name='نام موبایل به انگلیسی')),
                ('mobile_name_fa', models.CharField(max_length=50, verbose_name='نام موبایل به فارسی')),
                ('short_description', models.CharField(max_length=500, verbose_name='توضیحات کوتاه')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'هدر سایت',
                'verbose_name_plural': 'بخش مربوط به هدر سایت',
            },
        ),
    ]
