# Generated by Django 5.1.2 on 2024-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
