# Generated by Django 5.1.2 on 2024-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_header_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='نام موبایل')),
                ('Name_fa', models.CharField(max_length=50, verbose_name='نام موبایل به فارسی')),
                ('Size', models.CharField(max_length=10, verbose_name='اندازه ی محصول')),
                ('Network', models.CharField(max_length=10, verbose_name='نوع شبکه')),
                ('Ram', models.CharField(max_length=10, verbose_name='اندازه ی حافظه رم')),
                ('Color', models.BooleanField(default=False, verbose_name='رنگ بندی')),
                ('Guarantee', models.BooleanField(default=True, verbose_name='گارانتی')),
                ('Special_opportunity', models.BooleanField(default=False, verbose_name='فرصت ویژه')),
                ('Camera_resolution', models.CharField(max_length=10, verbose_name='رزولوشن دوربین')),
                ('Price', models.IntegerField(verbose_name='قیمت محصول')),
                ('Price_discount', models.BooleanField(default=False, verbose_name='تخفیف')),
                ('PriceByDiscount', models.IntegerField(verbose_name='قیمت تخفیف خورده ')),
                ('is_active', models.BooleanField(default=True, verbose_name='موجود')),
                ('Slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'ورود داده های محصولات',
            },
        ),
    ]
