# Generated by Django 5.1.2 on 2024-10-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=50, verbose_name='نام برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'نام برند',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50, verbose_name='دسته بندی')),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
            },
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='is_active',
            new_name='Is_active',
        ),
        migrations.AddField(
            model_name='mobile',
            name='Image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/', verbose_name='تصویر محصول'),
        ),
    ]
