# Generated by Django 5.1.2 on 2024-10-10 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_brand_category_rename_is_active_mobile_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Brands',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AddField(
            model_name='mobile',
            name='Brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pro_Brand', to='Shop.brands', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pro_Category', to='Shop.categories', verbose_name='دسته بندی '),
        ),
    ]
