# Generated by Django 5.1.2 on 2024-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_rename_brand_brands_rename_category_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Price',
            field=models.CharField(max_length=10, verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='PriceByDiscount',
            field=models.CharField(max_length=10, verbose_name='قیمت تخفیف خورده '),
        ),
    ]
