# Generated by Django 5.1.2 on 2024-10-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_mobile_network_alter_mobile_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='Camera_resolution',
            field=models.CharField(max_length=100, verbose_name='رزولوشن دوربین'),
        ),
    ]
