# Generated by Django 5.1.2 on 2024-10-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_mobile_pricebydiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Category_Slug',
            field=models.SlugField(default=''),
        ),
    ]
