# Generated by Django 5.1.2 on 2024-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_categories_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Category_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
