# Generated by Django 5.1.2 on 2024-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_categories_category_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Category_Slug',
            field=models.SlugField(),
        ),
    ]
