# Generated by Django 5.1.2 on 2024-10-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_brands_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'verbose_name': 'موبایل', 'verbose_name_plural': 'موبایل'},
        ),
        migrations.CreateModel(
            name='Mobile_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('Color', models.BooleanField(default=False, verbose_name='رنگ بندی')),
                ('Guarantee', models.BooleanField(default=True, verbose_name='گارانتی')),
                ('Special_opportunity', models.BooleanField(default=False, verbose_name='فرصت ویژه')),
                ('Price', models.CharField(max_length=10, verbose_name='قیمت محصول')),
                ('Price_discount', models.BooleanField(default=False, verbose_name='تخفیف')),
                ('PriceByDiscount', models.CharField(blank=True, max_length=10, null=True, verbose_name='قیمت تخفیف خورده ')),
                ('Is_active', models.BooleanField(default=True, verbose_name='موجود')),
                ('Image', models.ImageField(blank=True, default='', null=True, upload_to='media/', verbose_name='تصویر محصول')),
                ('Slug', models.SlugField(default='')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acces_Category', to='Shop.categories', verbose_name='دسته بندی ')),
            ],
            options={
                'verbose_name': 'لوازم جانبی',
                'verbose_name_plural': 'لوازم جانبی',
            },
        ),
    ]
